"""Agregando campos

Revision ID: b17119766f56
Revises: 
Create Date: 2022-04-06 15:31:26.676935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17119766f56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(length=255), nullable=True),
    sa.Column('apellido', sa.Text(length=255), nullable=True),
    sa.Column('telefono', sa.Text(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
