"""initial

Revision ID: a5f03771b091
Revises: 
Create Date: 2022-03-29 13:06:06.526757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f03771b091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Juguetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('mascotas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mascotas_id'], ['Mascotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Propietarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(length=125), nullable=True),
    sa.Column('mascotas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mascotas_id'], ['Mascotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Propietarios')
    op.drop_table('Juguetes')
    op.drop_table('Mascotas')
    # ### end Alembic commands ###
